# available palettes
#  "latte", "frappe", "macchiato", "mocha" :
palette: "mocha"

# custom css
# customCss: "css/custom.css":

subTitle: under construction

author: "e.j. sahala (they/them)"
description: "YACHT Another Custom Hugo Theme - YACHT is a recursively named, mobile-first, accessible, and responsive theme for the Hugo static site generator, using the Catppuccin color palette, and styled with BulmaCSS."

logoPicture: "yacht-logo.svg"
profilePicture: "yacht-logo.svg"
profilePictureAlt: "YACHT Another Custom Hugo Theme"
copyrightFrom: "2022"

# github integration
gh_user_api: "https://api.github.com/users"
gh_user: "ejsdotsh"

# charts
# mermaid: true

# LaTeX
# katex: true

# theme control
#  displayMode: "dark"
#  disableThemeSwitcher: true
#  doNotLoadAnimations: true
#  contentRatio: 0.7

# params.math:
# enable: true
# use: "katex"

## social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
social:
  - name: "linkedin"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/ejsdotsh/"
    weight: 10
  - name: "github"
    icon: "fab fa-github"
    url: "https://github.com/ejsdotsh/"
    weight: 20
  - name: "e-mail"
    icon: "fas fa-envelope"
    url: "mailto:contactme@ejs.sh"
    weight: 30
